[package]
name = "ewasm_api"
version = "0.4.0"
authors = ["Alex Beregszaszi <alex@rtfs.hu>"]
license = "Apache-2.0"
repository = "https://github.com/ewasm/ewasm-rust-api"
description = "ewasm API for Rust"
